### ISSUE TITLE
Slow members API is making the site feel sluggish

### ISSUE THREAD

**Issue by justinoboyle** [TCDG/collectivedev.com#18]
The endpoint that our site hits via AJAX to grab user data is `//devjoe.me/TCDG/members.php`, however it appears that this endpoint has an alarmingly high response time.

I tried to do a few diagnostic tests on the endpoint, but I couldn't even get it to reply to me half the time:

```
–––––––––––––––––––––––––––––––––––––––––––––––––––

Endpoint URL: https://devjoe.me/TCDG/members.php
Total number of requests sent and received: 256
Average response time: 0ms
Peak response time: 0ms
Lowest response time: 0ms

–––––––––––––––––––––––––––––––––––––––––––––––––––
```

We need to rethink this solution if it is going to be used in production.

**Comment by IDevJoe** [comment]
They said they were moving it. I believe the creds were revoked, I'm gonna take a look

**Comment by justinoboyle** [comment]
I think the point is more that it needs to support caching if we want to trust it at all; we aren't supposed to spam GitHub's servers.

**Comment by IDevJoe** [comment]
Rate limit was exceeded, Kelwing said he was gonna move it and start to use caching

**Comment by IDevJoe** [comment]
@Kelwing Remove the `ini_set` line in the TCDG copy.
@justinoboyle I've pointed the API on my domain to the one on the TCDG domain

**Comment by Kelwing** [comment]
The TCDG copy with caching is at https://collectivedev.com/members.php

**Comment by IDevJoe** [comment]
Caching on the new URL works, and I've redirected the old URL to the new URL

**Comment by JoeTheHuman** [comment]
Re-opened until the URL gets changed in the JS

**Comment by IDevJoe** [comment]
**Fixed**
