### ISSUE TITLE
https certs are broken

### ISSUE THREAD

**Issue by Gilbert142** [TCDG/collectivedev.com#3]
Whoever is in charge of collectivedev.com has enabled http to https redirects, but the cert is broken. Apart from that, HSTS is also enabled to we can't evade the browser warning.

**Comment by Gilbert142** [comment]
HSTS is disabled now, but the cert still has the wrong domain.

**Comment by inventor02** [comment]
Probably a cloudflare issue, do we use that?

**Comment by realshaunoneill** [comment]
Nope, we have our own dns server.

**Comment by BurritoWrapped** [comment]
Can confirm.

**Comment by BurritoWrapped** [comment]
@GilbertGobbels HSTS configuration is still cached in some browsers.

**Comment by GilbertGobbels** [comment]
@XeliteXirish @Kelwing HSTS is enabled again and the website unreachable. Fix this!

**Comment by realshaunoneill** [comment]
This is fixed now isnt it?
